### ISSUE TITLE
 Gzip / deflate compression

### ISSUE THREAD

**Issue by khusnetdinov** [symbiod/betterdocs#146]
Value: Improve SEO. Reduce response time with gzipped content

Possible solution: https://github.com/philnash/jekyll-gzip
use nginx

**Comment by sog01** [comment]
Please, show example regarding this. Thank you !

**Comment by khusnetdinov** [comment]
@sog01 This tasks requires investigation. If Jekyll can be used with deflating - implement. Or what example do you need?
